[target.'cfg(all())']
# Note: if the RUSTFLAGS environment variable is set, this will be
# ignored.
rustflags = [
          "-Dwarnings",
          "-Aunused-parens",
]

[target.stable-x86_64-pc-windows-msvc]
rustc-link-lib = ["user32"]
