[target.'cfg(all())']
# Note: if the RUSTFLAGS environment variable is set, this will be
# ignored.
rustflags = [
          "-Dwarnings",
          "-Aunused-parens",
]

[target.'cfg(windows)']
rustc-link-lib = ["user32"]
