name: release

on: push

jobs:
  ubuntu-release:
    runs-on: ubuntu-latest
    env:
      CARGO_HOME: /home/runner/.cargo
      PREFIX: /home/runner/install
    steps:
      - name: Linux Cargo Cache
        id: linux-cache-cargo
        uses: actions/cache@v4
        with:
          path: /home/runner/.cargo
          key: linux-cache-cargo
      - name: Install botan
        run: sudo apt install -y libbotan-2-dev
      - uses: actions/checkout@v4
      - run: sudo apt install cargo
      - run: make
      - run: make install
      - name: archive artifacts on sha
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-${{ github.sha }}
          path: /home/runner/install
      - name: archive artifacts on tag
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-${{ github.ref }}
          path: install

  windows-release:
    runs-on: windows-latest
    env:
      CARGO_HOME: "C:\\Users\\runneradmin\\.cargo"
    steps:
      - name: Get sources
        uses: actions/checkout@v4
      - name: Windows Cargo Cache
        id: windows-cache-cargo
        uses: actions/cache@v4
        with:
          path: "C:\\Users\\runneradmin\\.cargo"
          key: windows-cache-cargo
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Get botan
        uses: actions/download-artifact@v4
        with:
          name: windows-d39f573718993ceab57564e46dfacd4ad3017794
          github-token: ${{ secrets.ALL_REPO_ACCESS_TOKEN }}
          repository: plancksecurity/botan
          run-id: 7625124553
          path: .
      - name: Relocate lib
        run: cp lib\botan.lib botan.lib
      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
        env:
          RUSTFLAGS: -luser32
      - name: archive artifacts on sha
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ github.sha }}
          path: target\release
      - name: archive artifacts on tag
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ github.ref }}
          path: target\release

