name: release

on: push

jobs:
  ubuntu-release:
    runs-on: ubuntu-latest
    env:
      PREFIX: /home/runner/install
    steps:
      - name: Get botan 
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-d39f573718993ceab57564e46dfacd4ad3017794
          github-token: ${{ github.token }}
          repository: plancksecurity/botan
          run-id: 7625124553
          path: /home/runner/install
      - uses: actions/checkout@v4
      - run: sudo apt install cargo 
      - run: make
      - run: make install
      - name: archive artifacts on sha
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-${{ github.sha }}
          path: /home/runner/install
      - name: archive artifacts on tag
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-${{ github.ref }}
          path: install


